Add integration with Hugging Face
apple/ml-aim pull request #2
Opened 2024-01-18 11:25 UTC by NielsRogge

Hi,

Thanks for this nice work. I wrote a quick PoC to showcase that you can easily have integration so that you can automatically load the various AIM models using `from_pretrained` (and push them using `push_to_hub`), track download numbers for your models (similar to models in the Transformers library), and have nice model cards on a per-model basis. It leverages the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which allows to inherits these methods.

Usage is as follows:

```
from aim.models import AIMForImageClassification
from aim.torch.data import val_transforms
from PIL import Image

img = Image.open(...)
model = AIMForImageClassification.from_pretrained("apple/aim-600m")
transform = val_transforms()

inp = transform(img).unsqueeze(0)
logits, _ = model(inp)
```
I saw that currently download numbers won't be tracked since all checkpoints are just part of a single repository.

Would you be interested in this integration?

Kind regards,

Niels

2024-01-18 13:56 UTC, aelnouby commented
Thanks @NielsRogge, the plan sounds good. @michalk8 and I will provide a review for this PR shortly.

2024-01-18 17:19 UTC, michalk8 requested changes
Thanks a lot @NielsRogge , we'd be happy for your contribution!
Note that we switched from `src/aim` layout to just flat layout (`aim/`).

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/hub_mixin.py
> +"""Illustrates the mixin for one class."""
In general, all files should start with a license, please add.

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/__init__.py
> +from aim import mixins
There should be no need for this, would remove.

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/hub_mixin.py
> +"""Illustrates the mixin for one class."""
I think this example can be either added to `README.md` or let's create `examples` folder. In any case, I don't think it should be placed inside the package itself.

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> +class AttrDict(dict):
I'd add this to `aim/utils.py`

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> +class AIM(nn.Module):
This should still inherit the mixin, otherwise it breaks the API.

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> +class AIMForImageClassification(nn.Module, PyTorchModelHubMixin):
Unless I'm missing something, this should work without re-defining the `forward`, etc.:
```python
class AIMForImageClassification(mixins.AIMMixin, PyTorchModelHubMixin, nn.Module):
    ...
```

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> -from .. import mixins
Is there a reason for changing `from . import layers` to `import layers`? If not, prefer the latter.

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> +ArrayLike = Any
After using the mixin class, this should not be necessary.

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> +class AIMForImageClassification(nn.Module, PyTorchModelHubMixin):
Also please don't forget to add the `AIMForImageClassification` to `__all__`

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/models.py
> +    def __init__(self, config: dict):
config: Dict[str, Any]

2024-01-18 17:19 UTC, michalk8 commented on src/aim/pytorch/hub_mixin.py
> +import torch
Please install and run `pre-commit` for formatting.

2024-01-18 23:36 UTC, closed without merging

2024-01-20 09:18 UTC, kohlamor commented
Check my repository [Apple Books]